# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ecomm-iOS-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pod 'SwrveSDK'
pod 'SwrveGeoSDK'
pod 'SwrveSDKCommon'
pod 'UTIQ'
pod 'FunnelConnect'

  # Pods for Ecomm-iOS-App

end
